# Generated by Django 3.1.3 on 2020-11-05 09:19

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20201105_0822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True),
        ),
    ]
