# Generated by Django 3.1.3 on 2020-11-08 07:03

from django.db import migrations
import filebrowser.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20201107_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=filebrowser.fields.FileBrowseField(max_length=200, null=True),
        ),
    ]
