# Generated by Django 3.1.3 on 2020-11-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20201108_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='replaytocomment',
            name='content',
            field=models.TextField(),
        ),
    ]
