# Generated by Django 3.1.3 on 2020-11-08 21:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0013_auto_20201108_2122'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReplayToComment',
            new_name='Replay',
        ),
    ]
