# Generated by Django 3.1.3 on 2020-11-09 10:37

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20201109_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_pic',
            field=filebrowser.fields.FileBrowseField(blank=True, default='profile_pics/default.jpg', max_length=200, null=True),
        ),
    ]
