# Generated by Django 3.1.3 on 2020-11-09 10:48

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20201109_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_pic',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True),
        ),
    ]
