# Generated by Django 3.1.5 on 2021-01-20 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_remove_post_overview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Replay',
        ),
    ]
